const mongoose = require('mongoose');
const dotenv = require('dotenv');
const Product = require('./models/product'); // Assuming your Product model is in ./models/product.js

dotenv.config({ path: '.env.local' });

const DB_URI = process.env.MONGO_URI;

if (!DB_URI) {
  console.error('MONGO_URI not found in environment variables. Please set it.');
  process.exit(1);
}

const sampleProducts = [
  {
    name: 'Classic T-Shirt',
    slug: 'classic-t-shirt',
    description: 'A comfortable and stylish classic t-shirt made from 100% cotton.',
    basePrice: 25.00,
    salePrice: 20.00,
    category: 'Apparel',
    collections: ['Summer Collection'],
    tags: ['t-shirt', 'cotton', 'men', 'women'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'TSHIRT-BLK-S', color: '#000000', colorName: 'Black', size: 'S', stock: 50, images: ['/images/tshirt-black-s.jpg'] },
      { sku: 'TSHIRT-BLK-M', color: '#000000', colorName: 'Black', size: 'M', stock: 50, images: ['/images/tshirt-black-m.jpg'] },
      { sku: 'TSHIRT-WHT-S', color: '#FFFFFF', colorName: 'White', size: 'S', stock: 40, images: ['/images/tshirt-white-s.jpg'] },
    ],
  },
  {
    name: 'Denim Jeans',
    slug: 'denim-jeans',
    description: 'Durable and fashionable denim jeans for everyday wear.',
    basePrice: 0,
    salePrice: 0,
    category: 'Apparel',
    collections: ['Winter Collection'],
    tags: ['jeans', 'denim', 'men'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'JEANS-BLU-30', color: '#0000FF', colorName: 'Blue', size: 'M', stock: 30, images: ['/images/jeans-blue-30.jpg'] },
      { sku: 'JEANS-BLU-32', color: '#0000FF', colorName: 'Blue', size: 'L', stock: 30, images: ['/images/jeans-blue-32.jpg'] },
    ],
  },
  {
    name: 'Leather Wallet',
    slug: 'leather-wallet',
    description: 'Premium leather wallet with multiple card slots.',
    basePrice: 50.00,
    category: 'Accessories',
    collections: [],
    tags: ['wallet', 'leather', 'accessories'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'WALLET-BRN-OS', color: '#A52A2A', colorName: 'Brown', size: 'OS', stock: 20, images: ['/images/wallet-brown.jpg'] },
    ],
  },
  {
    name: 'Summer Dress',
    slug: 'summer-dress',
    description: 'Light and airy dress perfect for summer days.',
    basePrice: 0,
    category: 'Apparel',
    collections: ['Summer Collection'],
    tags: ['dress', 'women', 'summer'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'DRESS-RED-S', color: '#FF0000', colorName: 'Red', size: 'S', stock: 25, images: ['/images/dress-red-s.jpg'] },
      { sku: 'DRESS-RED-M', color: '#FF0000', colorName: 'Red', size: 'M', stock: 25, images: ['/images/dress-red-m.jpg'] },
    ],
  },
    {
    name: 'Wool Scarf',
    slug: 'wool-scarf',
    description: 'Warm and soft wool scarf for chilly weather.',
    basePrice: 35.00,
    salePrice: 28.00,
    category: 'Accessories',
    collections: ['Winter Collection'],
    tags: ['scarf', 'wool', 'winter'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SCARF-GRY-OS', color: '#808080', colorName: 'Grey', size: 'OS', stock: 40, images: ['/images/scarf-grey.jpg'] },
    ],
  },
  {
    name: 'Running Shoes',
    slug: 'running-shoes',
    description: 'Lightweight and comfortable running shoes for your daily jog.',
    basePrice: 90.00,
    category: 'Footwear',
    collections: ['Sports Collection'],
    tags: ['shoes', 'running', 'sport'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'SHOES-BLK-8', color: '#000000', colorName: 'Black', size: '8', stock: 20, images: ['/images/shoes-black-8.jpg'] },
      { sku: 'SHOES-BLK-9', color: '#000000', colorName: 'Black', size: '9', stock: 20, images: ['/images/shoes-black-9.jpg'] },
      { sku: 'SHOES-WHT-8', color: '#FFFFFF', colorName: 'White', size: '8', stock: 15, images: ['/images/shoes-white-8.jpg'] },
    ],
  },
  {
    name: 'Casual Hoodie',
    slug: 'casual-hoodie',
    description: 'Soft cotton hoodie perfect for casual wear.',
    basePrice: 45.00,
    salePrice: 38.00,
    category: 'Apparel',
    collections: ['Autumn Collection'],
    tags: ['hoodie', 'casual', 'men', 'women'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'HOODIE-NAV-S', color: '#000080', colorName: 'Navy', size: 'S', stock: 30, images: ['/images/hoodie-navy-s.jpg'] },
      { sku: 'HOODIE-NAV-M', color: '#000080', colorName: 'Navy', size: 'M', stock: 30, images: ['/images/hoodie-navy-m.jpg'] },
    ],
  },
  {
    name: 'Leather Belt',
    slug: 'leather-belt',
    description: 'Classic genuine leather belt with a metal buckle.',
    basePrice: 30.00,
    category: 'Accessories',
    collections: [],
    tags: ['belt', 'leather'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'BELT-BLK-32', color: '#000000', colorName: 'Black', size: '32', stock: 25, images: ['/images/belt-black-32.jpg'] },
      { sku: 'BELT-BRN-34', color: '#A52A2A', colorName: 'Brown', size: '34', stock: 25, images: ['/images/belt-brown-34.jpg'] },
    ],
  },
  {
    name: 'Sports Socks (3-pack)',
    slug: 'sports-socks-3-pack',
    description: 'Breathable and comfortable sports socks, 3 pairs.',
    basePrice: 15.00,
    salePrice: 12.00,
    category: 'Accessories',
    collections: ['Sports Collection'],
    tags: ['socks', 'sport'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SOCKS-WHT-M', color: '#FFFFFF', colorName: 'White', size: 'M', stock: 60, images: ['/images/socks-white-m.jpg'] },
    ],
  },
  {
    name: 'Winter Coat',
    slug: 'winter-coat',
    description: 'Heavy-duty winter coat to keep you warm in extreme cold.',
    basePrice: 180.00,
    category: 'Apparel',
    collections: ['Winter Collection'],
    tags: ['coat', 'winter', 'men', 'women'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'COAT-BLK-M', color: '#000000', colorName: 'Black', size: 'M', stock: 15, images: ['/images/coat-black-m.jpg'] },
      { sku: 'COAT-BLK-L', color: '#000000', colorName: 'Black', size: 'L', stock: 15, images: ['/images/coat-black-l.jpg'] },
    ],
  },
  {
    name: 'Sunglasses',
    slug: 'sunglasses',
    description: 'Stylish UV-protected sunglasses for sunny days.',
    basePrice: 60.00,
    category: 'Accessories',
    collections: ['Summer Collection'],
    tags: ['sunglasses', 'eyewear'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SUN-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 35, images: ['/images/sunglasses-black.jpg'] },
    ],
  },
  {
    name: 'Formal Shirt',
    slug: 'formal-shirt',
    description: 'Crisp cotton formal shirt for office or special occasions.',
    basePrice: 55.00,
    salePrice: 45.00,
    category: 'Apparel',
    collections: [],
    tags: ['shirt', 'formal', 'men'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SHIRT-WHT-M', color: '#FFFFFF', colorName: 'White', size: 'M', stock: 25, images: ['/images/shirt-white-m.jpg'] },
      { sku: 'SHIRT-BLU-L', color: '#0000FF', colorName: 'Blue', size: 'L', stock: 20, images: ['/images/shirt-blue-l.jpg'] },
    ],
  },
  {
    name: 'Backpack',
    slug: 'backpack',
    description: 'Durable and spacious backpack for daily use or travel.',
    basePrice: 75.00,
    category: 'Accessories',
    collections: [],
    tags: ['backpack', 'bag', 'travel'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'BACKPACK-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 30, images: ['/images/backpack-black.jpg'] },
    ],
  },
  {
    name: 'Swim Trunks',
    slug: 'swim-trunks',
    description: 'Quick-drying swim trunks for beach and pool.',
    basePrice: 30.00,
    salePrice: 25.00,
    category: 'Apparel',
    collections: ['Summer Collection'],
    tags: ['swimwear', 'men', 'summer'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SWIM-BLU-M', color: '#0000FF', colorName: 'Blue', size: 'M', stock: 30, images: ['/images/swim-blue-m.jpg'] },
      { sku: 'SWIM-GRN-L', color: '#008000', colorName: 'Green', size: 'L', stock: 25, images: ['/images/swim-green-l.jpg'] },
    ],
  },
  {
    name: 'Yoga Mat',
    slug: 'yoga-mat',
    description: 'Non-slip yoga mat for comfortable practice.',
    basePrice: 25.00,
    category: 'Sports Equipment',
    collections: ['Sports Collection'],
    tags: ['yoga', 'fitness'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'YOGA-PUR-OS', color: '#800080', colorName: 'Purple', size: 'OS', stock: 20, images: ['/images/yoga-purple.jpg'] },
    ],
  },
  {
    name: 'Bluetooth Headphones',
    slug: 'bluetooth-headphones',
    description: 'Wireless headphones with clear sound and long battery life.',
    basePrice: 120.00,
    category: 'Electronics',
    collections: [],
    tags: ['headphones', 'bluetooth', 'audio'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'HEAD-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 10, images: ['/images/headphones-black.jpg'] },
    ],
  },
  {
    name: 'Rain Jacket',
    slug: 'rain-jacket',
    description: 'Waterproof and breathable rain jacket for outdoor activities.',
    basePrice: 85.00,
    salePrice: 70.00,
    category: 'Apparel',
    collections: ['Outdoor Collection'],
    tags: ['jacket', 'rain', 'outdoor'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'RAIN-YEL-M', color: '#FFFF00', colorName: 'Yellow', size: 'M', stock: 20, images: ['/images/rainjacket-yellow-m.jpg'] },
    ],
  },
  {
    name: 'Travel Mug',
    slug: 'travel-mug',
    description: 'Insulated travel mug to keep your drinks hot or cold.',
    basePrice: 20.00,
    category: 'Home Goods',
    collections: [],
    tags: ['mug', 'travel', 'kitchen'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'MUG-STL-OS', color: '#C0C0C0', colorName: 'Stainless Steel', size: 'OS', stock: 50, images: ['/images/mug-steel.jpg'] },
    ],
  },
  {
    name: 'Graphic T-Shirt',
    slug: 'graphic-t-shirt',
    description: 'Unique graphic print t-shirt made from soft cotton.',
    basePrice: 28.00,
    category: 'Apparel',
    collections: ['Summer Collection'],
    tags: ['t-shirt', 'graphic', 'men', 'women'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'GTSHIRT-WHT-S', color: '#FFFFFF', colorName: 'White', size: 'S', stock: 30, images: ['/images/gtshirt-white-s.jpg'] },
      { sku: 'GTSHIRT-BLK-M', color: '#000000', colorName: 'Black', size: 'M', stock: 30, images: ['/images/gtshirt-black-m.jpg'] },
    ],
  },
  {
    name: 'Smartwatch',
    slug: 'smartwatch',
    description: 'Feature-rich smartwatch with health tracking and notifications.',
    basePrice: 250.00,
    salePrice: 200.00,
    category: 'Electronics',
    collections: [],
    tags: ['smartwatch', 'wearable', 'tech'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'SMARTW-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 10, images: ['/images/smartwatch-black.jpg'] },
    ],
  },
  {
    name: 'Casual Sneakers',
    slug: 'casual-sneakers',
    description: 'Comfortable and stylish sneakers for everyday casual wear.',
    basePrice: 70.00,
    category: 'Footwear',
    collections: [],
    tags: ['sneakers', 'casual', 'shoes'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SNEAK-GRY-7', color: '#808080', colorName: 'Grey', size: '7', stock: 20, images: ['/images/sneakers-grey-7.jpg'] },
      { sku: 'SNEAK-GRY-8', color: '#808080', colorName: 'Grey', size: '8', stock: 20, images: ['/images/sneakers-grey-8.jpg'] },
    ],
  },
  {
    name: 'Denim Jacket',
    slug: 'denim-jacket',
    description: 'Classic denim jacket, a timeless addition to any wardrobe.',
    basePrice: 95.00,
    category: 'Apparel',
    collections: ['Autumn Collection'],
    tags: ['jacket', 'denim', 'men', 'women'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'DJACKET-BLU-S', color: '#4682B4', colorName: 'Blue', size: 'S', stock: 20, images: ['/images/denimjacket-blue-s.jpg'] },
      { sku: 'DJACKET-BLU-M', color: '#4682B4', colorName: 'Blue', size: 'M', stock: 20, images: ['/images/denimjacket-blue-m.jpg'] },
    ],
  },
  {
    name: 'Water Bottle',
    slug: 'water-bottle',
    description: 'Reusable stainless steel water bottle, 750ml.',
    basePrice: 18.00,
    salePrice: 15.00,
    category: 'Home Goods',
    collections: ['Sports Collection'],
    tags: ['bottle', 'hydration', 'eco-friendly'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'BOTTLE-STL-OS', color: '#C0C0C0', colorName: 'Stainless Steel', size: 'OS', stock: 40, images: ['/images/bottle-steel.jpg'] },
    ],
  },
  {
    name: 'Dress Pants',
    slug: 'dress-pants',
    description: 'Comfortable and stylish dress pants for formal occasions.',
    basePrice: 65.00,
    category: 'Apparel',
    collections: [],
    tags: ['pants', 'formal', 'men'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'DPANTS-BLK-32', color: '#000000', colorName: 'Black', size: '32', stock: 20, images: ['/images/dresspants-black-32.jpg'] },
      { sku: 'DPANTS-GRY-34', color: '#808080', colorName: 'Grey', size: '34', stock: 20, images: ['/images/dresspants-grey-34.jpg'] },
    ],
  },
  {
    name: 'Portable Charger',
    slug: 'portable-charger',
    description: 'High-capacity portable charger for your devices on the go.',
    basePrice: 40.00,
    salePrice: 32.00,
    category: 'Electronics',
    collections: [],
    tags: ['charger', 'powerbank', 'tech'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'PCHARG-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 25, images: ['/images/charger-black.jpg'] },
    ],
  },
  {
    name: 'Beanie Hat',
    slug: 'beanie-hat',
    description: 'Warm knitted beanie hat for winter.',
    basePrice: 20.00,
    category: 'Accessories',
    collections: ['Winter Collection'],
    tags: ['hat', 'beanie', 'winter'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'BEANIE-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 30, images: ['/images/beanie-black.jpg'] },
    ],
  },
  {
    name: 'Canvas Tote Bag',
    slug: 'canvas-tote-bag',
    description: 'Eco-friendly canvas tote bag for shopping or daily use.',
    basePrice: 12.00,
    salePrice: 10.00,
    category: 'Accessories',
    collections: ['Eco-Friendly'],
    tags: ['bag', 'tote', 'canvas'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'TOTE-NAT-OS', color: '#F5DEB3', colorName: 'Natural', size: 'OS', stock: 50, images: ['/images/tote-natural.jpg'] },
    ],
  },
  {
    name: 'Wireless Earbuds',
    slug: 'wireless-earbuds',
    description: 'Compact wireless earbuds with charging case.',
    basePrice: 80.00,
    category: 'Electronics',
    collections: [],
    tags: ['earbuds', 'wireless', 'audio'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'EARBUDS-WHT-OS', color: '#FFFFFF', colorName: 'White', size: 'OS', stock: 15, images: ['/images/earbuds-white.jpg'] },
    ],
  },
  {
    name: 'Polo Shirt',
    slug: 'polo-shirt',
    description: 'Classic polo shirt made from breathable pique cotton.',
    basePrice: 35.00,
    salePrice: 30.00,
    category: 'Apparel',
    collections: ['Summer Collection'],
    tags: ['polo', 'shirt', 'men'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'POLO-BLU-M', color: '#0000FF', colorName: 'Blue', size: 'M', stock: 30, images: ['/images/polo-blue-m.jpg'] },
      { sku: 'POLO-GRN-L', color: '#008000', colorName: 'Green', size: 'L', stock: 25, images: ['/images/polo-green-l.jpg'] },
    ],
  },
  {
    name: 'Desk Lamp',
    slug: 'desk-lamp',
    description: 'Modern LED desk lamp with adjustable brightness.',
    basePrice: 50.00,
    category: 'Home Goods',
    collections: [],
    tags: ['lamp', 'desk', 'lighting'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'LAMP-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 20, images: ['/images/lamp-black.jpg'] },
    ],
  },
  {
    name: 'Hiking Boots',
    slug: 'hiking-boots',
    description: 'Durable waterproof hiking boots for rugged trails.',
    basePrice: 150.00,
    category: 'Footwear',
    collections: ['Outdoor Collection'],
    tags: ['boots', 'hiking', 'outdoor'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'HBOOTS-BRN-9', color: '#A52A2A', colorName: 'Brown', size: '9', stock: 15, images: ['/images/hikingboots-brown-9.jpg'] },
      { sku: 'HBOOTS-BRN-10', color: '#A52A2A', colorName: 'Brown', size: '10', stock: 15, images: ['/images/hikingboots-brown-10.jpg'] },
    ],
  },
  {
    name: 'Leather Gloves',
    slug: 'leather-gloves',
    description: 'Soft leather gloves for driving or winter wear.',
    basePrice: 40.00,
    category: 'Accessories',
    collections: ['Winter Collection'],
    tags: ['gloves', 'leather', 'winter'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'GLOVES-BLK-M', color: '#000000', colorName: 'Black', size: 'M', stock: 20, images: ['/images/gloves-black-m.jpg'] },
    ],
  },
  {
    name: 'Casual Dress Shirt',
    slug: 'casual-dress-shirt',
    description: 'Versatile dress shirt for smart-casual occasions.',
    basePrice: 48.00,
    salePrice: 40.00,
    category: 'Apparel',
    collections: [],
    tags: ['shirt', 'casual', 'men'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'CDSHIRT-WHT-M', color: '#FFFFFF', colorName: 'White', size: 'M', stock: 25, images: ['/images/cdshirt-white-m.jpg'] },
      { sku: 'CDSHIRT-BLU-L', color: '#ADD8E6', colorName: 'Light Blue', size: 'L', stock: 20, images: ['/images/cdshirt-blue-l.jpg'] },
    ],
  },
  {
    name: 'Portable Speaker',
    slug: 'portable-speaker',
    description: 'Compact portable Bluetooth speaker with powerful sound.',
    basePrice: 60.00,
    category: 'Electronics',
    collections: [],
    tags: ['speaker', 'bluetooth', 'audio'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'PSPEAKER-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 15, images: ['/images/speaker-black.jpg'] },
    ],
  },
  {
    name: 'Sun Hat',
    slug: 'sun-hat',
    description: 'Wide-brimmed sun hat for ultimate sun protection.',
    basePrice: 25.00,
    category: 'Accessories',
    collections: ['Summer Collection'],
    tags: ['hat', 'sun', 'summer'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'SUNHAT-BEI-OS', color: '#F5F5DC', colorName: 'Beige', size: 'OS', stock: 30, images: ['/images/sunhat-beige.jpg'] },
    ],
  },
  {
    name: 'Track Pants',
    slug: 'track-pants',
    description: 'Comfortable track pants for sports or lounging.',
    basePrice: 40.00,
    salePrice: 30.00,
    category: 'Apparel',
    collections: ['Sports Collection'],
    tags: ['pants', 'track', 'sport'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'TPANTS-BLK-M', color: '#000000', colorName: 'Black', size: 'M', stock: 30, images: ['/images/trackpants-black-m.jpg'] },
      { sku: 'TPANTS-GRY-L', color: '#808080', colorName: 'Grey', size: 'L', stock: 25, images: ['/images/trackpants-grey-l.jpg'] },
    ],
  },
  {
    name: 'Coffee Maker',
    slug: 'coffee-maker',
    description: 'Programmable drip coffee maker for your morning brew.',
    basePrice: 70.00,
    category: 'Home Goods',
    collections: [],
    tags: ['coffee', 'kitchen', 'appliance'],
    isFeatured: true,
    isActive: true,
    variants: [
      { sku: 'COFFEE-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 10, images: ['/images/coffeemaker-black.jpg'] },
    ],
  },
  {
    name: 'Wristwatch',
    slug: 'wristwatch',
    description: 'Classic analog wristwatch with a leather strap.',
    basePrice: 100.00,
    category: 'Accessories',
    collections: [],
    tags: ['watch', 'analog', 'leather'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'WATCH-BRN-OS', color: '#A52A2A', colorName: 'Brown', size: 'OS', stock: 20, images: ['/images/wristwatch-brown.jpg'] },
    ],
  },
  {
    name: 'Blouse',
    slug: 'blouse',
    description: 'Elegant women\'s blouse for various occasions.',
    basePrice: 40.00,
    salePrice: 35.00,
    category: 'Apparel',
    collections: [],
    tags: ['blouse', 'women', 'formal'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'BLOUSE-WHT-S', color: '#FFFFFF', colorName: 'White', size: 'S', stock: 25, images: ['/images/blouse-white-s.jpg'] },
      { sku: 'BLOUSE-BLU-M', color: '#ADD8E6', colorName: 'Light Blue', size: 'M', stock: 20, images: ['/images/blouse-blue-m.jpg'] },
    ],
  },
  {
    name: 'Gaming Mouse',
    slug: 'gaming-mouse',
    description: 'High-precision gaming mouse with customizable buttons.',
    basePrice: 50.00,
    category: 'Electronics',
    collections: ['Gaming'],
    tags: ['mouse', 'gaming', 'pc'],
    isFeatured: false,
    isActive: true,
    variants: [
      { sku: 'GMOUSE-BLK-OS', color: '#000000', colorName: 'Black', size: 'OS', stock: 15, images: ['/images/gamingmouse-black.jpg'] },
    ],
  },
];

async function seedProducts() {
  try {
    console.log(`Attempting to connect to MongoDB with URI: ${DB_URI.replace(/:[^@]+@/, ':********@')}`);
    await mongoose.connect(DB_URI, {
      useNewUrlParser: true,
      useUnifiedTopology: true,
    });
    console.log('MongoDB Connected for seeding...');

    // Clear existing products to avoid duplicates during testing
    await Product.deleteMany({});
    console.log('Existing products cleared.');

    await Product.insertMany(sampleProducts);
    console.log(`${sampleProducts.length} sample products inserted successfully.`);

  } catch (error) {
    console.error('Error seeding products:', error);
  } finally {
    mongoose.disconnect();
    console.log('MongoDB Disconnected.');
  }
}

seedProducts();