import dotenv from 'dotenv';
import path from 'path';

// Load env vars
dotenv.config({ path: path.join(__dirname, '../../.env.local') });
dotenv.config({ path: path.join(__dirname, '../../.env') });

import { supabase } from '../database/connect';

const collectionsData = [
  {
    name: 'New Arrivals',
    slug: 'new-arrivals',
    description: 'Curated avant-garde arrivals for the current season.',
    longDescription: 'Experience the latest iterations of modern fashion. Our new arrivals blend technological innovation with traditional couture craftsmanship.',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000',
    accentColor: 'from-cyan-500/20 to-blue-600/20',
    displayOrder: 1,
    isActive: true,
    seoTitle: 'New Luxury Arrivals - Plasma Atelier',
    seoDescription: 'Discover the latest avant-garde arrivals from Plasma Atelier.',
  },
  {
    name: 'Summer Edit',
    slug: 'summer-edit',
    description: 'Futuristic resort and hot-weather wear designed for comfort.',
    longDescription: 'Keep cool with high-tech fabrics and silhouettes styled for high-temperature cyber-resorts.',
    image: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?q=80&w=1000',
    accentColor: 'from-orange-500/20 to-yellow-600/20',
    displayOrder: 2,
    isActive: true,
    seoTitle: 'Luxury Summer Collection - Plasma Atelier',
    seoDescription: 'Futuristic resort wear and high-tech summer garments.',
  },
  {
    name: 'Evening Couture',
    slug: 'evening-couture',
    description: 'High-end elegant tailoring for after-dark statement-making.',
    longDescription: 'Stunning silhouettes and hyper-premium tailoring made for night events and luxury lounges.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?q=80&w=1000',
    accentColor: 'from-purple-500/20 to-pink-600/20',
    displayOrder: 3,
    isActive: true,
    seoTitle: 'Evening Couture & Tailoring - Plasma Atelier',
    seoDescription: 'Hyper-premium evening wear and elegant night statement couture.',
  },
  {
    name: 'Digital Couture',
    slug: 'digital-couture',
    description: 'AI runway couture built on generative aesthetics.',
    longDescription: 'Exploring the boundary between digital fashion design and physical garment creation.',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?q=80&w=1000',
    accentColor: 'from-blue-500/20 to-purple-600/20',
    displayOrder: 4,
    isActive: true,
    seoTitle: 'Digital Couture & Generative Fashion - Plasma Atelier',
    seoDescription: 'Generative and digital couture crossing the screen to reality.',
  },
  {
    name: 'Editorial Picks',
    slug: 'editorial-picks',
    description: 'Pieces recommended by our head designers.',
    longDescription: 'Curated favorites from our creative directors, showcasing bold styling and premium craftsmanship.',
    image: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1469334031218-e382a71b716b?q=80&w=1000',
    accentColor: 'from-amber-500/20 to-red-600/20',
    displayOrder: 5,
    isActive: true,
    seoTitle: 'Designers Editorial Picks - Plasma Atelier',
    seoDescription: 'Browse pieces curated and selected directly by our head designers.',
  },
  {
    name: 'Limited Edition',
    slug: 'limited-edition',
    description: 'Highly restricted, serial-numbered releases.',
    longDescription: 'Extremely rare items crafted in single-digit production batches for the ultimate collectors.',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?q=80&w=1000',
    accentColor: 'from-rose-500/20 to-indigo-600/20',
    displayOrder: 6,
    isActive: true,
    seoTitle: 'Limited Edition Collectibles - Plasma Atelier',
    seoDescription: 'Discover and shop rare limited serial releases.',
  },
  {
    name: 'AI Collection',
    slug: 'ai-collection',
    description: 'Designs conceptualized by custom generative neural models.',
    longDescription: 'At the intersection of code and canvas, this capsule showcases designs purely generated by deep learning algorithms.',
    image: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1539109136881-3be0616acf4b?q=80&w=1000',
    accentColor: 'from-emerald-500/20 to-teal-600/20',
    displayOrder: 7,
    isActive: true,
    seoTitle: 'AI Conceptual Couture - Plasma Atelier',
    seoDescription: 'Capsules conceptualized and curated via neural models.',
  },
  {
    name: 'Heritage Collection',
    slug: 'heritage-collection',
    description: 'Timeless luxury roots combined with cybernetic details.',
    longDescription: 'Honoring historical patterns and techniques, upgraded with futuristic design elements.',
    image: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000',
    bannerImage: 'https://images.unsplash.com/photo-1549298916-b41d501d3772?q=80&w=1000',
    accentColor: 'from-bronze-500/20 to-yellow-700/20',
    displayOrder: 8,
    isActive: true,
    seoTitle: 'Heritage Capsule Collection - Plasma Atelier',
    seoDescription: 'Traditional techniques meet futuristic visions.',
  },
];

async function seed() {
  try {
    console.log('Clearing existing collections...');
    await supabase.from('collections').delete().neq('id', '00000000-0000-0000-0000-000000000000');
    await supabase.from('collection_products').delete().neq('collection_id', '00000000-0000-0000-0000-000000000000');

    console.log('Seeding collections...');
    // Fetch products to associate
    const { data: products } = await supabase.from('products').select('*');

    for (const c of collectionsData) {
      const matchingProducts = (products || []).filter((p) => {
        return (
          p.collections.includes(c.slug) ||
          p.collections.includes(c.name)
        );
      });

      const featuredProductIds = matchingProducts.slice(0, 3).map((p) => p.id);

      const { data: collection, error } = await supabase
        .from('collections')
        .insert({
          name: c.name,
          title: c.name,
          slug: c.slug,
          description: c.description,
          long_description: c.longDescription,
          image: c.image,
          banner_image: c.bannerImage,
          accent_color: c.accentColor,
          featured_products: featuredProductIds,
          product_count: matchingProducts.length,
          display_order: c.displayOrder,
          is_active: c.isActive,
        })
        .select()
        .single();

      if (error || !collection) {
        throw new Error(`Failed to seed collection ${c.name}: ${error?.message}`);
      }

      if (matchingProducts.length > 0) {
        const links = matchingProducts.map((p) => ({
          collection_id: collection.id,
          product_id: p.id,
        }));
        await supabase.from('collection_products').insert(links);
      }

      console.log(`Seeded collection: ${c.name} with ${matchingProducts.length} associated products.`);
    }

    console.log('Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

seed();
